// A slash command, a `!` command, and the plumbing around both.
//
// Running `/model` or `!gcloud auth login` in a Claude Code terminal does not
// record one message, it records four: a caveat telling the agent to ignore
// what follows, the command's name, its message, its arguments, and then
// whatever it printed — and the harness injects `<system-reminder>` and
// `<task-notification>` blocks of its own besides. zevet showed every one as
// prose, so a conversation read back as XML and sessions were titled "Caveat:
// The messages below were generated by the user while running local
// commands…".
//
// EVERY FIXTURE BELOW IS A REAL LINE, lifted from ~/.claude/projects and
// ~/.codex/sessions on 2026-09-22 — including the ANSI a `/compact` notice
// arrives dressed in and the empty-stdout-plus-stderr shape a failed `!`
// command leaves. They go through the SAME functions the board renders with:
// `readEnvelope` is what components/slashtext.tsx calls, `sessionTranscript`
// is what the conversation view is built from, and `sessionLabel` /
// `sessionBlurb` / `unwrapEnvelope` are the rail and the mission line.
import { test, describe } from "node:test";
import assert from "node:assert/strict";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { createRequire } from "node:module";
import { ROOT } from "./helpers.mjs";

const lib = (name) =>
  import(pathToFileURL(path.join(ROOT, "board", "src", "lib", name)).href);

const { readEnvelope, stripAnsi } = await lib("envelope.mjs");
const { sessionTranscript, sessionLabel, sessionBlurb, unwrapEnvelope } = await lib("sessions.mjs");
const require = createRequire(import.meta.url);
const reader = require(path.join(ROOT, "desktop", "agent-sessions.js"));

/** A `user` record exactly as desktop/agent-sessions.js hands it over. */
const said = (content) => ({
  source: "claude",
  type: "user",
  uuid: "u1",
  timestamp: "2026-09-22T00:00:00.000Z",
  message: { role: "user", content },
});

const CAVEAT =
  "<local-command-caveat>Caveat: The messages below were generated by the user while " +
  "running local commands. DO NOT respond to these messages or otherwise consider them " +
  "in your response unless the user explicitly asks you to.</local-command-caveat>";

const MODEL =
  "<command-name>/model</command-name>\n            <command-message>model</command-message>" +
  "\n            <command-args></command-args>";

const COMPACTED =
  "<local-command-stdout>\u001b[2mCompacted (ctrl+o to see full summary)\u001b[22m\n" +
  "\u001b[2mPreCompact hook failed\u001b[22m</local-command-stdout>";

describe("the envelope a terminal session records a command in", () => {
  test("a slash command is its name and its arguments, nothing else", () => {
    assert.deepEqual(readEnvelope(MODEL), { kind: "command", name: "/model", args: "" });
    // The blocks arrive in either order, and `/max` is a custom command — the
    // record IS the proof it ran, so there is no list to check it against.
    assert.deepEqual(
      readEnvelope("<command-message>max</command-message>\n<command-name>/max</command-name>"),
      { kind: "command", name: "/max", args: "" },
    );
    // A skill is recorded without the slash it was invoked with.
    assert.deepEqual(
      readEnvelope(
        "<command-message>workflow-authoring</command-message>\n" +
          "<command-name>workflow-authoring</command-name>\n<skill-format>true</skill-format>",
      ),
      { kind: "command", name: "/workflow-authoring", args: "" },
    );
    assert.deepEqual(
      readEnvelope(
        "<command-name>/model</command-name><command-args>opus</command-args>",
      ),
      { kind: "command", name: "/model", args: "opus" },
    );
  });

  test("a caveat, a reminder and a task notification are never anything", () => {
    assert.deepEqual(readEnvelope(CAVEAT), { kind: "noise" });
    assert.deepEqual(readEnvelope("<system-reminder>be nice</system-reminder>"), { kind: "noise" });
    assert.deepEqual(
      readEnvelope(
        "<task-notification>\n<task-id>a2ecf3f4d0199ab57</task-id>\n" +
          "<status>completed</status>\n<summary>Agent \"Hub relay\" finished</summary>\n" +
          "</task-notification>",
      ),
      { kind: "noise" },
    );
    // codex's own two, from ~/.codex/sessions.
    assert.deepEqual(readEnvelope("<user_instructions>AGENTS.md…</user_instructions>"), {
      kind: "noise",
    });
  });

  test("command output keeps its words and loses its escape codes", () => {
    assert.deepEqual(readEnvelope(COMPACTED), {
      kind: "out",
      text: "Compacted (ctrl+o to see full summary)\nPreCompact hook failed",
      error: false,
    });
    assert.deepEqual(readEnvelope("<local-command-stdout>Login successful</local-command-stdout>"), {
      kind: "out",
      text: "Login successful",
      error: false,
    });
    // A `!` command that failed: stdout is present but empty, stderr has it.
    assert.deepEqual(
      readEnvelope(
        "<bash-stdout></bash-stdout><bash-stderr>/usr/bin/bash: line 2: gcloud: command not found\n</bash-stderr>",
      ),
      { kind: "out", text: "/usr/bin/bash: line 2: gcloud: command not found", error: true },
    );
    // One that printed nothing at all said nothing at all.
    assert.deepEqual(readEnvelope("<bash-stdout></bash-stdout><bash-stderr></bash-stderr>"), {
      kind: "noise",
    });
    assert.deepEqual(readEnvelope("<bash-input>gcloud auth login</bash-input>"), {
      kind: "bash",
      command: "gcloud auth login",
    });
    assert.equal(stripAnsi("\u001b[2mdim\u001b[22m"), "dim");
    // A command run under a Windows shell prints CRLF, and the summary line is
    // one line — a lone \r in it is a carriage return nothing comes back from.
    assert.deepEqual(readEnvelope("<bash-stdout>one\r\ntwo\r\n</bash-stdout>"), {
      kind: "out",
      text: "one\ntwo",
      error: false,
    });
  });

  test("a message with words of its own is not an envelope", () => {
    // These go to the PEEL in sessions.mjs instead, which takes leading blocks
    // off something a person then typed. Confusing the two would swallow asks.
    assert.equal(readEnvelope("why does <div> collapse?"), null);
    assert.equal(readEnvelope(`${CAVEAT}\n\nkeep the tests green`), null);
    assert.equal(readEnvelope("<ide_opened_file>notes.txt</ide_opened_file>\n\nread it"), null);
    // Truncated — a live prompt's `detail` is cut, so the block never closes.
    assert.equal(readEnvelope("<task-notification>\n<task-id>b1</task-id>"), null);
    assert.equal(readEnvelope(""), null);
  });
});

describe("what the conversation shows for a session run from a terminal", () => {
  test("the plumbing is gone and the command is one chip", () => {
    const { messages } = sessionTranscript([
      said(CAVEAT),
      said(MODEL),
      said("<local-command-stdout>Set model to `Fable 5.1`</local-command-stdout>"),
      said("<system-reminder>The user opened a file.</system-reminder>"),
      said("now make the rail readable"),
    ]);
    // Five records in, three messages out: the caveat and the reminder are not
    // things anybody said.
    assert.deepEqual(
      messages.map((m) => m.content[0].text),
      [MODEL, "<local-command-stdout>Set model to `Fable 5.1`</local-command-stdout>", "now make the rail readable"],
    );
    // The two that survive are still envelopes, which is what slashtext.tsx
    // reads to draw a chip and a collapsed line rather than markdown.
    assert.equal(readEnvelope(messages[0].content[0].text).kind, "command");
    assert.equal(readEnvelope(messages[1].content[0].text).kind, "out");
    assert.equal(readEnvelope(messages[2].content[0].text), null);
  });

  test("a reminder stapled to a real ask loses the reminder, not the ask", () => {
    const { messages } = sessionTranscript([
      said("ship the rail\n<system-reminder>Be concise.</system-reminder>"),
    ]);
    assert.equal(messages[0].content[0].text, "ship the rail");
    // But a compaction summary that merely NAMES the tag in prose keeps it:
    // only a closed block is cut, and this one is a backticked mention.
    const mention = "each `<system-reminder>` says it is not user input";
    assert.equal(sessionTranscript([said(mention)]).messages[0].content[0].text, mention);
  });

  test("a whole session of nothing but plumbing is an empty conversation", () => {
    assert.deepEqual(sessionTranscript([said(CAVEAT), said("<system-reminder>x</system-reminder>")]).messages, []);
  });
});

describe("how a session that starts with a command is named", () => {
  test("by its first real prompt, or by the command when there is none", () => {
    assert.equal(sessionLabel({ prompt: MODEL }), "/model");
    assert.equal(sessionBlurb({ prompt: MODEL }), "/model");
    assert.equal(
      sessionLabel({ prompt: "<command-name>/model</command-name><command-args>opus</command-args>" }),
      "/model opus",
    );
    // The caveat names nothing, so the row falls through to the id rather than
    // reading our own plumbing out loud.
    assert.equal(sessionLabel({ prompt: CAVEAT, id: "abc" }), "abc");
    assert.equal(sessionLabel({ prompt: COMPACTED, id: "abc" }), "abc");
    // A `!` command is something a person ran, so it is allowed to name a row.
    assert.equal(sessionLabel({ prompt: "<bash-input>npm test</bash-input>" }), "! npm test");
    // And the mission line on the People rail is the same peel.
    assert.equal(unwrapEnvelope(MODEL), "/model");
    assert.equal(unwrapEnvelope(CAVEAT), "");
  });

  test("the reader skips the caveat and keeps the command as the fallback", () => {
    // desktop/agent-sessions.js takes ONE user record as a session's `prompt`,
    // and it used to be the first — which for any session started with a
    // slash command is the caveat. The three piles, in the order a file has
    // them: plumbing is skipped, a command is held, an ask wins.
    const texts = [CAVEAT, MODEL, "now make the rail readable"];
    assert.equal(reader._firstAsk(texts), "now make the rail readable");
    // With no ask after it, the command names the session — as the chip, once
    // the board has read it.
    assert.equal(unwrapEnvelope(reader._firstAsk(texts.slice(0, 2))), "/model");
    // What a command printed never names anything, and neither does silence.
    assert.equal(reader._firstAsk([CAVEAT, COMPACTED]), "");
    assert.equal(reader._firstAsk([]), "");
  });
});
