// GENERATED by @masora/desktop-kit from the IPC table. Do not edit; change the table.
import type { SessionsResult, SessionResult, SessionAgentsResult } from "./sessions.d.mts";
import type { LocalWorkspace, LocalEntry, UsableAgent, ColorThemeSpec } from "./types";
import type { ReadResult, StartAgentResult, StatsResult, AgentSchedule, SchedulesResult, CommitsResult, IndexSearchResult, MemoriesResult, PermitRequest, AgentSettings, AgentSettingsResult, StatusResult, AskRequest, AgentEvent, HeldConsole, ChatSummary, StoredChat, ZevetConfig } from "./bridge";

export interface ZevetBridge {
  /**
   * The saved settings, REDACTED, or null on a first run.
   *
   * `{ hub, actor, hasSecret, legacy }` — never the secret and never the token.
   * `actor` is here because the board needs it to label a remote cursor with a
   * person's name rather than a client number, and a display name is not a
   * credential. See `zevet:config` in main.js for what this call used to return
   * and why it stopped.
   */
  config: () => Promise<ZevetConfig | null | undefined>;
  /** Ask the hub whether this URL and token actually work, before saving them. */
  test?(hub: unknown, token: unknown): Promise<unknown>;
  /** Write ~/.zevet/config.json. */
  save?(hub: unknown, token: unknown, actor: unknown): Promise<unknown>;
  /**
   * Sign in with GitHub.
   *
   * `githubStart` resolves with `{ userCode, url }` as soon as GitHub has
   * issued a code, and the main process has already opened the browser on it.
   * `githubWait` then resolves when the person has clicked Authorize — up to
   * fifteen minutes later — and by the time it does, the config is written.
   *
   * ⚠️ NEITHER CALL RETURNS THE SECRET OR THE SESSION, on purpose and for the
   * same reason `config()` redacts them: the BOARD window loads HTML from the
   * hub, so anything on this bridge is something a hub that has been taken over
   * can read out of its own page. The renderer is told a login and a yes.
   */
  githubStart: (hub?: string | null, team?: string) => Promise<{ ok?: boolean; error?: string; userCode?: string }>;
  githubWait: () => Promise<{ ok?: boolean; cancelled?: boolean; error?: string; login?: string }>;
  githubCancel: () => void;
  /** End this machine's GitHub session, hub-side and locally. */
  githubLogout?: () => Promise<{ ok?: boolean; error?: string } | null | undefined>;
  /**
   * Mint a brand new, independently-owned team on the given hub — see
   *  main.js's `zevet:teamCreate` and hub/server.mjs's `/team/create`.
   *  Resolves `{ ok, team }` or `{ ok: false, error }`.
   */
  teamCreate?(hub: unknown, name: unknown): Promise<unknown>;
  teamResolve?(hub: unknown, name: unknown): Promise<unknown>;
  /**
   * Redeem a per-invitee key — hub/server.mjs's `/team/join`. Resolves
   *  `{ ok, login, owner, teamName }` or `{ ok: false, error }`; the secret
   *  and session are written to config by the main process and never handed
   *  to this window, same rule as githubWait/googleWait above.
   */
  teamJoin?(team: unknown, key: unknown): Promise<unknown>;
  /**
   * Sign in with Google.
   *
   * Same shape as the GitHub trio and one difference worth knowing: there is no
   * `userCode`, because Google's web flow never shows the person a code.
   * `googleStart` resolves with `{ url, domain }` once the hub has minted a
   * pairing code and the main process has opened the browser; `googleWait` then
   * resolves when the browser has come back to the hub, and by then the config
   * is written.
   *
   * ⚠️ NEITHER CALL RETURNS THE SECRET OR THE SESSION — the same rule as the
   * GitHub pair, for the same reason.
   *
   * The same three calls for Google. The flow differs — the hub owns the
   * callback, so `googleStart` hands back a URL to open rather than a code to
   * type — but the app's side of it is the same start / wait / cancel.
   */
  googleStart?: (hub?: string | null, team?: string) => Promise<{ ok?: boolean; error?: string; url?: string; expiresIn?: number; domain?: string }>;
  googleWait?: () => Promise<{ ok?: boolean; cancelled?: boolean; error?: string; login?: string; owner?: boolean }>;
  googleCancel?: () => void;
  /**
   * End this machine's session, hub-side and locally. A session does not
   *  remember which provider minted it, so this is the same call as
   *  `githubLogout` under the name the Google button expects.
   */
  googleLogout?: () => Promise<{ ok?: boolean; error?: string } | null | undefined>;
  /**
   * Sign in with Microsoft (Entra ID or a personal Microsoft account). Exactly
   * Google's shape — the hub owns the callback, so `microsoftStart` hands back a URL
   * opened by the main process and `microsoftWait` resolves once the config is written.
   * Neither call returns the secret or the session.
   */
  microsoftStart?: (hub?: string | null, team?: string) => Promise<{ ok?: boolean; error?: string; url?: string; expiresIn?: number; domain?: string }>;
  microsoftWait?: () => Promise<{ ok?: boolean; cancelled?: boolean; error?: string; login?: string; owner?: boolean }>;
  microsoftCancel?: () => void;
  /** End this machine's session; the same call as `githubLogout` and `googleLogout`. */
  microsoftLogout?: () => Promise<{ ok?: boolean; error?: string } | null | undefined>;
  /** Send what the person typed plus the scrubbed tail of the app log to Sentry. `{ ok }`. */
  sendReport?: (text: string) => Promise<{ ok: boolean }>;
  /**
   * Leave the team entirely: ends the hub session, then drops session,
   *  secret AND hub from config.json (backed up first) so this machine
   *  falls back to first-run setup. See main.js's `signOutTeam`.
   *
   * Leave the team on this machine — drops session, secret and hub from
   *  config.json (backed up first) and returns to first-run setup.
   */
  signOutTeam?: () => Promise<{ ok?: boolean; error?: string } | null | undefined>;
  /**
   * Linking with Masora (T5, docs/contracts/cross_app_context.md). The link
   * runs in the main process in the background; the renderer reads its status
   * and can retry or open the approval page. The token is written straight to
   * the OS keychain there and this bridge has no call that reads it back.
   *
   * Linking with Masora (T5, docs/contracts/cross_app_context.md). The link
   * runs in the background in the main process; this reads its status. No call
   * returns a token -- it is written straight to the OS keychain there.
   */
  masoraConfig?: () => Promise<{ url: string; paired: boolean; member?: string; repos: Record<string, boolean>; chat?: boolean }>;
  masoraSaveUrl?: (url: string) => Promise<{ url: string; paired: boolean; repos: Record<string, boolean> }>;
  masoraLinkStatus?: () => Promise<{ phase: string; paired?: boolean; code?: string; error?: string }>;
  masoraLinkStart?: () => Promise<{ phase: string; paired?: boolean; code?: string; error?: string }>;
  masoraLinkApprove?: () => Promise<boolean>;
  masoraUnpair?: () => Promise<boolean>;
  /** Settings: the one line saying why this machine's agents are not reaching the team hub, or an empty string when they are. */
  reportingStatus?: () => Promise<{ problem: string }>;
  /**
   * Family panel: one row per sibling app, and the click on its chip.
   *
   * Family panel (desktop/family.js).
   */
  familyStatus?: () => Promise<unknown[]>;
  familyAct?: (app: string, action: string) => Promise<{ ok?: boolean; download?: string | null; requested?: boolean; pairing?: string } | undefined>;
  /** Zevet Chat push to Masora (C1 `zevet_chat`), off by default. */
  masoraChatPush?: (on: boolean) => Promise<{ url: string; paired: boolean; repos: Record<string, boolean>; chat?: boolean }>;
  /**
   * Connections panel: which sources are linked, and connecting a new one.
   * Channel names have no "zevet:" prefix -- they are `masora:sources` /
   * `masora:connect`, matching main.js's own registration.
   *
   * Connections panel: linked-source status, and connecting a new one.
   */
  masoraSources?: () => Promise<{ sources?: { kind: string; status: string }[]; error?: string }>;
  masoraConnect?: (arg: { provider: string }) => Promise<{ ok?: boolean; error?: string }>;
  /**
   * Model credentials (D-0NN). `listCredentials` merges team (fetched from
   * the hub) and personal (this machine's own safeStorage-encrypted store,
   * desktop/credentials.js) into one metadata-only list, plus the member's
   * chosen default. `addCredential`/`removeCredential` take `{scope}` of
   * "team" or "personal"; a personal secret never crosses this bridge except
   * as the `key` the person just typed, going IN.
   *
   * Model credentials (D-0NN): team (hub-held) and personal (this machine
   *  only, safeStorage-encrypted) merged into one metadata-only list, never
   *  a secret. `default` is this member's chosen spawn credential, if any —
   *  {scope:"personal"|"team", id} or {scope:"auto"} to use the ladder.
   */
  listCredentials?: () => Promise<{
    ok?: boolean;
    credentials?: Array<{
      id: string;
      scope: "team" | "personal";
      label: string;
      provider: string;
      kind: string;
      last4: string;
      addedBy?: string;
      createdAt?: string;
    }>;
    default?: { scope: "team" | "personal" | "auto"; id?: string } | null;
    error?: string;
  }>;
  addCredential?: (arg: {
    scope: "team" | "personal";
    label?: string;
    provider: string;
    kind: string;
    key: string;
  }) => Promise<{ ok?: boolean; id?: string; error?: string }>;
  removeCredential?: (arg: { scope: "team" | "personal"; id: string }) => Promise<{ ok?: boolean; error?: string }>;
  setDefaultCredential?: (
    arg: { scope: "team" | "personal"; id: string } | { scope: "auto" } | null,
  ) => Promise<{ ok?: boolean; default?: unknown }>;
  /**
   * "Auto" mode's rotation ladder — an ordered [{credentialId, untilPct}].
   *  See desktop/credential-ladder.js for how it is walked.
   *
   * The "Auto" rotation ladder — an ordered list of {credentialId, untilPct}.
   */
  credentialLadder?: () => Promise<Array<{ credentialId: string; untilPct: number }>>;
  setCredentialLadder?: (
    ladder: Array<{ credentialId: string; untilPct: number }>,
  ) => Promise<{ ok?: boolean; ladder?: Array<{ credentialId: string; untilPct: number }> }>;
  /** Native folder picker; resolves to a path or null. */
  pickRepo?(): Promise<unknown>;
  /** Install the hooks into that repo. */
  install?(repo: unknown): Promise<unknown>;
  /** Setup is finished — open the board. */
  done?(): Promise<unknown>;
}

export interface LocalBridge {
  available: boolean;
  /** The folders this machine has opened, most recent first. */
  workspaces: () => Promise<LocalWorkspace[]>;
  /** Native folder picker; adds it to the list. */
  addWorkspace: () => Promise<LocalWorkspace | null>;
  /**
   * C1's per-repo opt-in (`zevet.masoraRepos`), keyed by resolved folder
   *  path; default none.
   *
   * C1's per-repo opt-in, keyed by resolved folder path; default none.
   */
  masoraRepos?: () => Promise<Record<string, boolean>>;
  masoraRepoToggle?: (root: string, on: boolean) => Promise<{ ok: boolean; error?: string; repos?: Record<string, boolean> }>;
  /** A file tree under one of those folders. */
  tree: (dir: string) => Promise<{ ok: boolean; entries?: LocalEntry[]; truncated?: boolean; origin?: string; error?: string }>;
  /** One text file, by path relative to its root. */
  read: (root: string, relPath: string) => Promise<ReadResult>;
  /**
   * One text file back, by path relative to its root.
   *
   * SAID PLAINLY, because it changes what this bridge is: the board window
   * loads a REMOTE origin — the hub's own page — with this preload attached.
   * openBoard() in main.js sets out why that is considered acceptable (the hub
   * already ships the hook that runs on every teammate's machine, so it is
   * trusted with code execution already, and a narrow bridge makes a capability
   * it effectively had explicit and bounded instead of implicit).
   *
   * That reasoning was written about READING files. This adds writing them, and
   * the stakes of the same decision are now higher: a hostile hub page could
   * not merely see your source, it could change it, inside a folder you picked.
   * The decision stands and is not being reopened here. It is written down so
   * that whoever does reopen it is looking at the real stake.
   *
   * `opts` is `{ bom, eol }` as `read` reported them, so a file goes back the
   * way it came. main.js keeps only those two fields; nothing else crosses.
   */
  write: (root: string, relPath: string, text: string, opts: { bom?: boolean; eol?: string }) => Promise<{ ok: boolean; error?: string }>;
  /**
   * Added-line hunks for one file: `{ ok, hunks: [{start, count}] }`. Read-only
   *  git metadata about a picked folder — narrower than tree/read/write above.
   */
  diffHunks?: (root: string, rel: string) => Promise<{ ok: boolean; hunks?: Array<{ start?: number }> }>;
  /**
   * Line counts and git diff stats for a list of paths under one root.
   *
   * `{ ok, lines: {rel: number|null}, diff: {rel: {added, removed, status}} | null }`.
   * `lines[rel]` is null for a file that was not counted — too big, binary or
   * unreadable — which is a different thing from zero. `diff` is null when git
   * said nothing useful at all (not a repo, no git, a timeout); an EMPTY diff
   * object means a clean tree, and the two must not be drawn the same way.
   *
   * Capped in the main process at 2000 paths per call, with `truncated` saying
   * so. Counting is synchronous there, so an uncapped call from here could
   * freeze the window.
   *
   *
   * The status strip's machine-side figures. `root` is optional and only
   * affects the branch segment; it is re-checked against the opened
   * workspaces in the main process, as every path on this bridge is.
   *
   * Tell the native window what colour the page just became.
   */
  chrome: (spec: ColorThemeSpec) => void;
  /**
   * Staying current. `updateInstall` is the only one with a consequence, and
   * it is reachable only from a button the person presses -- nothing here
   * runs an installer on a timer. See desktop/app-update.js for what that
   * does per platform, and for what the published checksum does not buy.
   */
  updateStatus: () => Promise<unknown>;
  updateCheck: () => Promise<unknown>;
  updateInstall: () => Promise<{ ok?: boolean; manual?: boolean; error?: string }>;
  /**
   * The code index. Every one of these is inert on a machine the capability
   * gate turned down, and `indexEnable` is the ONLY thing that fetches the
   * model -- nothing here starts a download on its own.
   */
  indexStatus: (root: string | null) => Promise<{ ok: boolean } & Record<string, unknown>>;
  indexEnable?: (root: string | null) => Promise<{ ok?: boolean; indexed?: number; skipped?: number; error?: string } | null | undefined>;
  /**
   * Semantic search over the workspace index. The scores are real cosines —
   *  `code-index.js` clamps them to [-1, 1] — which is why a retrieval panel
   *  can print one. Optional: a build without the index capability has none.
   * `filter` narrows by PATH and is matched as a literal, case-insensitively
   *  — it is not a pattern. See main.js § pathFilter: a regex from here runs
   *  against every chunk on the main process, where one that backtracks takes
   *  the whole app with it.
   */
  indexSearch?: (root: string | null, query: string, opts?: { k?: number; filter?: string }) => Promise<IndexSearchResult>;
  status: (root: string | null) => Promise<StatusResult>;
  stats: (root: string, paths: string[]) => Promise<StatsResult>;
  /** The last few commits, newest first. Read only — there is no restore. */
  commits?: (root: string, limit?: number) => Promise<CommitsResult>;
  /**
   * What the agent has written down about this repo, if it writes memories
   *  at all. Read only: there is no bridge call that deletes one.
   */
  memories?: (root: string) => Promise<MemoriesResult>;
  /**
   * Every agent session on this machine — claude and codex, terminal,
   *  desktop app and IDE alike. Read only.
   *
   * Every agent session on this machine — claude and codex, terminal, desktop
   *  app and IDE alike. Read only: there is no bridge call that writes or
   *  deletes one, and a session the CLI still has open is being appended to.
   *  Optional: an older desktop build has neither, and the pane that lists
   *  them renders nothing without them.
   */
  sessions?: (opts?: { cwd?: string | null; limit?: number }) => Promise<SessionsResult>;
  session?: (source: string, slug: string, id: string, child?: string) => Promise<SessionResult>;
  /**
   * The subagents a claude session spawned, each openable as `session(..., child)`.
   *
   * The subagents a claude session spawned. Open one by passing its id as
   *  `session`'s fourth argument.
   */
  sessionAgents?: (slug: string, id: string) => Promise<SessionAgentsResult>;
  /**
   * A running console's title and (codex) real context, off its session file.
   *
   * A running console's own title and, for codex, its real context — see
   *  desktop/agent-sessions.js § live. Null until the CLI has written a file.
   */
  sessionLive?: (
    source: string,
    id: string,
  ) => Promise<{
    title: string;
    context: number | null;
    cached: number | null;
    output: number | null;
    window: number | null;
    model?: string;
    effort?: string;
    account?: string;
  } | null>;
  /**
   * Masora Voice: is it installed, and start it so its flow bar comes up.
   * See desktop/masora-voice.js for why there is no "start recording".
   * The permission posture a new agent starts with, saved beside the zoom in
   * ~/.zevet/config.json. Returns what is now stored, so the settings pane can
   * show the truth rather than what it hoped for.
   *
   * Save this user default permission posture. Returns what is now stored —
   * never assume the write landed, which is the whole reason it answers.
   */
  defaultMode: (mode: string) => Promise<{ ok?: boolean; error?: string; mode?: string }>;
  voiceStatus?(): Promise<unknown>;
  voiceStart?(): Promise<unknown>;
  voiceMic?(): Promise<unknown>;
  /**
   * A follow-up to a console whose process has exited. All three CLIs can
   *  resume a session by id (measured 2026-09-21); codex and opencode need a
   *  new process to do it, which is what this is. Optional: an older desktop
   *  build has no resume, and the composer falls back to refusing.
   */
  resumeAgent?: (
    name: string,
    root: string,
    resumeFrom: string,
    opts: { model: string; mode: string; continues?: string },
  ) => Promise<StartAgentResult>;
  /**
   * Standing instructions for this repo, and which optional capabilities an
   *  agent started here is given. Optional: an older desktop build has none,
   *  and the panel that edits them renders nothing without it.
   */
  agentSettings?: (root: string) => Promise<AgentSettingsResult>;
  saveAgentSettings?: (root: string, patch: Partial<AgentSettings>) => Promise<AgentSettingsResult>;
  /**
   * Every "zevet.*" localStorage key, mirrored on this machine so it follows
   *  the person across a reload, an app update, or a change of hub.
   *
   * Every "zevet.*" localStorage key, mirrored on this machine. Optional: an
   *  older desktop build has neither, and `zStorage` below is then exactly
   *  `window.localStorage`.
   */
  prefs?: () => Promise<Record<string, string>>;
  setPref?: (key: string, value: string | null) => Promise<unknown>;
  /**
   * Seed the mirror in one round trip — an existing user upgrading from a
   *  build without it has every pref sitting only in localStorage.
   *
   * Seed the mirror in one batch — see prefs-mirror.mjs's `hydratePrefsMirror`,
   *  called once for an existing user upgrading from a build without it.
   */
  setPrefs?: (entries: Record<string, string>) => Promise<unknown>;
  /**
   * Agent runs on a timer. Optional: an older desktop build does not have
   *  them, and the hub serves this board to whatever version is installed.
   */
  schedules?: () => Promise<SchedulesResult>;
  scheduleSave?: (s: Partial<AgentSchedule>) => Promise<SchedulesResult>;
  scheduleRemove?: (id: string) => Promise<SchedulesResult>;
  scheduleToggle?: (id: string) => Promise<SchedulesResult>;
  /**
   * Tell me when something else changes this file on disk.
   *
   * THE SOMETHING ELSE IS THE POINT: Claude Code and Codex are editing these
   * files while the editor has them open. Without this the next keystroke
   * publishes the stale text over the agent's work and nothing anywhere reports
   * it. Idempotent — watching an already-watched file is a no-op, not a second
   * stream of events.
   */
  watch: (root: string, relPath: string, lastWritten: string | null) => Promise<{ ok: boolean }>;
  unwatch: (root: string, relPath: string) => Promise<unknown>;
  /** Which agents are installed on this machine. */
  agents: () => Promise<UsableAgent[]>;
  /** Start an agent in a folder. Returns { ok, id }. */
  startAgent: (name: string, root: string, opts: { model: string; mode: string; forkFrom?: string; prompt?: string; effort?: string; addDirs?: string[]; continueLatest?: boolean; engine?: string; label?: string }) => Promise<StartAgentResult>;
  sendToAgent: (id: string, text: string) => Promise<{ ok: boolean; error?: string }>;
  boardReply?: (reqId: string, result: unknown) => Promise<unknown>;
  stopAgent: (id: string) => Promise<unknown>;
  /**
   * The consoles still held by this app, with every event each has sent —
   *  what a reloaded board replays to pick them back up.
   *
   * What the app still holds from before a reload. Optional: an older desktop
   *  build reaps its agents on reload instead.
   */
  consoles?: () => Promise<{ seq: number; consoles: HeldConsole[] }>;
  forgetAgent?: (id: string) => Promise<unknown>;
  /**
   * Zevet Chat (desktop/chat.js): repo-independent conversations.
   *
   * Zevet Chat (desktop/chat.js). Optional: an older desktop build has none,
   * and the Code | Chat switch is then not offered.
   */
  chatList?: (query?: string) => Promise<ChatSummary[]>;
  chatGet?: (id: string) => Promise<StoredChat | null>;
  chatCreate?: (folder?: string) => Promise<StoredChat>;
  chatSetFolder?: (id: string, folder: string) => Promise<ChatSummary | null>;
  chatRename?: (id: string, title: string) => Promise<ChatSummary | null>;
  chatRemove?: (id: string) => Promise<boolean>;
  chatSend?: (
    id: string,
    text: string,
    opts?: { agent?: string; model?: string; effort?: string; mode?: string },
  ) => Promise<{ ok: boolean; error?: string; brief?: boolean }>;
  chatStop?: (id: string) => Promise<unknown>;
  permitAnswer?: (id: string, allow: boolean, reason?: string, always?: boolean) => Promise<{ ok: boolean; error?: string }>;
  /**
   * Answered ONCE, with the chosen LABELS. Answering twice is harmless on the
   * wire — the main process has already deleted the pending entry — but the
   * UI must not be able to, which is why the card is removed optimistically.
   */
  askAnswer?: (id: string, picked: string[]) => Promise<{ ok: boolean; error?: string }>;
  /**
   * Steer a teammate's agent (D-058): main seals the text with the document
   * key and sends it through the hub, which enforces the team's steer policy.
   * Optional: an older desktop build cannot steer.
   */
  steerSend?: (to: string, session: string, repo: string, text: string) => Promise<{ ok: boolean; id?: string; status?: string; approval?: boolean; error?: string }>;
  steerAnswer?: (id: string, approve: boolean) => Promise<{ ok: boolean; error?: string }>;
  onUpdate: (cb: (s: unknown) => void) => void;
  onIndexEvent: (cb: (p: { kind?: string; total?: number; loaded?: number; indexed?: number }) => void) => void;
  /**
   * `fn({ root, relPath, text, bytes, bom, eol })`; returns an unsubscribe.
   *
   * `bom` and `eol` are carried so they can be handed straight back to `write`:
   * a file that arrived with a BOM and CRLF has to be saved that way or the
   * next commit is a whole-file diff blamed on whoever pressed save.
   *
   * A DELETED file produces no event. There is no text to carry and sending an
   * empty string would tell the editor to publish an empty document — the exact
   * clobber this exists to prevent. See `fire()` in desktop/file-watch.js.
   */
  onFileChanged: (cb: (p: { root: string; relPath: string; text?: string; bom?: boolean; eol?: string }) => void) => () => void;
  /**
   * A due schedule just ran (or was skipped); the board's own list is
   * otherwise only refreshed after a save/toggle/remove round-trip.
   */
  onSchedulesChanged?: (cb: (list: unknown) => void) => () => void;
  onChatEvent?: (cb: (p: { id: string; evt: { type: string; [k: string]: unknown } }) => void) => () => void;
  /** Stream of console events; returns an unsubscribe function. */
  onAgentEvent: (cb: (evt: AgentEvent) => void) => () => void;
  /**
   * A console the board did not start itself (the loopback agent API, a schedule)
   * just opened. Without it such an agent only reached the board on a page reload.
   */
  onAgentAttached?: (cb: (c: HeldConsole) => void) => () => void;
  /**
   * The loopback agent API asks the board to start or message an agent through
   * its own actions, as a person's Send would. Answer with boardReply.
   */
  onBoardRequest?: (cb: (req: { reqId: string; kind: string; [k: string]: unknown }) => void) => () => void;
  /**
   * An agent is asking to do something and is BLOCKED until the answer comes
   * back — see the computer-use block in main.js. The board is the only place
   * a person can be asked, so this is not a notification.
   *
   * An agent is asking permission and is waiting on the answer. Optional: a
   *  build without computer use never sends one.
   */
  onPermitRequest?: (cb: (req: PermitRequest) => void) => () => void;
  /**
   * An agent has asked the PERSON something (not a yes/no permission — a
   * question with its own options) and is blocked on the answer. Same shape
   * as the permit channel above, different event names.
   *
   * A question from an agent, and the answer back. Optional like the permit
   * pair beside them: an older main process simply never sends one.
   */
  onAskRequest?: (cb: (req: AskRequest) => void) => () => void;
  /**
   * Steering (D-058): `ask` an approval card for a teammate's steer, `done`
   * when one was injected or declined, `status` for a steer this person sent.
   */
  onSteerEvent?: (cb: (e: { kind: string; id: string; [k: string]: unknown }) => void) => () => void;
}

export interface ZevetDocBridge {
  available: boolean;
  /** Join a room and start receiving it. `{ ok, error?, code? }`. */
  join?(room: unknown): Promise<unknown>;
  /**
   * Send one plaintext Yjs update. `opts.snapshot` marks it as a full state
   * that the hub may replace the room's whole log with — which is what keeps
   * a long-lived room from being trimmed out from under a late joiner.
   */
  send?(room: unknown, u8: unknown, opts: unknown): Promise<unknown>;
  /** Publish this room's unresolved comments to ~/.zevet/comments/<repo>/<path>.json, where agents can read them. `{ ok }`. */
  comments?(room: unknown, data: unknown): Promise<unknown>;
  /**
   * Leave. Always `{ ok: true }`; leaving a room never joined is what a
   *  closing tab does and is not worth an error.
   */
  leave?(room: unknown): Promise<unknown>;
  /**
   * `fn({ room, kind, bytes? })`; returns an unsubscribe.
   *
   *   `ready`         the socket is open and joined — send your full state now,
   *                   which is what seeds an empty room and what gets offline
   *                   edits to everyone else.
   *   `update`        `bytes` is a plaintext Yjs update from a teammate.
   *   `snapshot-due`  send your whole document with `{snapshot:true}`.
   *
   * ⚠️ `ready` FIRES ON EVERY RECONNECT, not once. After a hub restart the
   * renderer is asked for its state again, and that is the mechanism by which
   * the room refills rather than a duplicate to be filtered out.
   */
  onMessage?: (fn: (payload: unknown) => void) => () => void;
  /**
   * `fn({ room, state, detail })`; returns an unsubscribe. The ONLY place a
   *  connection problem is reported — an editor that silently stops syncing is
   *  this project's worst failure, so the status is a first-class output.
   */
  onStatus?: (fn: (payload: unknown) => void) => () => void;
}
