// Finder needs a native bookmark on current APFS/macOS. The Python bookmark
// generated by the pinned dmg-builder parses, but Foundation cannot resolve it.
import Foundation

guard CommandLine.arguments.count == 4 else {
    fatalError("Usage: dmg-bookmark.swift create|verify background bookmark")
}
let mode = CommandLine.arguments[1]
let background = URL(fileURLWithPath: CommandLine.arguments[2]).standardizedFileURL
let bookmark = URL(fileURLWithPath: CommandLine.arguments[3])
if mode == "create" {
    let data = try background.bookmarkData(options: [], includingResourceValuesForKeys: nil, relativeTo: nil)
    try data.write(to: bookmark)
} else if mode != "verify" {
    fatalError("Unknown bookmark operation")
}
var stale = false
let resolved = try URL(resolvingBookmarkData: Data(contentsOf: bookmark),
    options: [.withoutUI, .withoutMounting], relativeTo: nil, bookmarkDataIsStale: &stale)
guard resolved.resolvingSymlinksInPath() == background.resolvingSymlinksInPath(),
      FileManager.default.fileExists(atPath: resolved.path) else {
    fatalError("Finder's background bookmark does not resolve to the installed image")
}
print("Finder background bookmark resolves to the mounted image")
